Update defaults.jl to use 1.9
oscar-system/OscarDevTools.jl pull request #31
Opened 2023-07-10 10:42 UTC by lgoettgens

Cf. https://github.com/oscar-system/Oscar.jl/pull/2533

2023-07-10 11:09 UTC, benlorenz requested changes

2023-07-10 11:09 UTC, benlorenz commented on src/defaults.jl
> +    :Singular        => [v"0.18.3"     => (v"1.9", v"1.10" )],
```suggestion
    :Oscar           => [v"0.12.1-DEV" => (v"1.8", v"1.11"),
                         v"0.13.0-DEV" => (v"1.9", v"1.12")],
    :Hecke           => [v"0.16.7"     => (v"1.8", v"1.9" )],
    :AbstractAlgebra => [v"0.29.5"     => (v"1.8", v"1.9" )],
    :Nemo            => [v"0.33.8"     => (v"1.8", v"1.9" )],
    :Singular        => [v"0.18.3"     => (v"1.8", v"1.9" )],
```
This is wrong, please don't just bump all these versions.

This is a dictionary that indicates which package versions can be doctested on which julia version. If we remove 1.8 from the doctests in oscar we should add a new entry to the array at `:Oscar` with the current Oscar version and `(v"1.9", v"1.12")`. (1.12 since nightly is 1.11 now and we do doctests with nightly)

For the other packages this should be done similarly. Once the doctest version in the corresponding repo is changed we can add a new entry here that indicates version and doctest-compatibility.

I suggested the correct line for Oscar, but would prefer to keep the other versions like this until this is tested in the corresponding repo. (If the version is not compatible the doctests will just be skipped, if we add a line without having checked it we might get some annoying errors in the tests)

2023-07-10 11:19 UTC, lgoettgens commented on src/defaults.jl
> +    :Singular        => [v"0.18.3"     => (v"1.9", v"1.10" )],
ok, thanks for the explanation. I would suggest to just wait a few hours until the PRs in the other repos are merged and then we can change it here for most of them at once.

2023-07-11 16:31 UTC, lgoettgens commented on src/defaults.jl
> +    :Singular        => [v"0.18.3"     => (v"1.9", v"1.10" )],
If I understand the comment above correctly, your suggestion does not work as intended as the first match is taken, i.e. new versions should be added to the front. I already updated this for Oscar and AA.

2023-07-11 16:36 UTC, benlorenz commented on src/defaults.jl
> +    :Singular        => [v"0.18.3"     => (v"1.9", v"1.10" )],
Indeed, thanks, I remembered it the wrong way around.

2023-07-13 13:26 UTC, lgoettgens commented
@benlorenz I updated the `doctest_versions` dictionary entries for all packages. The left side is the version in the corresponding `Project.toml` at the time of merging the PR that changes the doctest version there.
This should resolve your requested changes.

Is there anything else blocking this PR?

2023-07-13 13:40 UTC, benlorenz approved these changes
> @benlorenz I updated the `doctest_versions` dictionary entries for all packages. The left side is the version in the corresponding `Project.toml` at the time of merging the PR that changes the doctest version there. This should resolve your requested changes.

Strictly speaking using the next version or an intermediate version would be better, but since none of the packages required any changes for the bump this should be fine.

> Is there anything else blocking this PR?

No, thanks for taking care of this.

2023-07-13 14:36 UTC, merged